- a few chages to fix syntax errors within runQueue and enqueue - moved the conf file into it own etc directory - renamed runJobs to scheduleJobs to more correctly reflect it operation

diff --git a/bin/enqueue b/bin/enqueue
--- a/bin/enqueue
+++ b/bin/enqueue
@@ -26,12 +26,16 @@
 # execution queue.  This is done by making a checksum as part of the queued
 # file's name, and searching the queues for any file with an identical
 # checksum
+#
+# return code:  0     success
+#               1     error
+#               100   job already queued - enqueue cancelled
 ###############################################################################
 
 ###############################################################################
 # get user defined globals
 ###############################################################################
-. ${0%/*}/server.conf
+. ${0%/*}/../etc/server.conf
 
 # redefine $SUDO to include the configured user
 SUDO=""
@@ -104,7 +108,6 @@ shortestQueue () {
 COMMAND_PATH=`$READLINK -f "$0"`
 COMMAND_PARMS=( "$@" )
 
-checkRunningUser
 if [ $# -eq 0 ]; then
     printFullUsage
 fi
@@ -128,7 +131,9 @@ isDup=`find $QUEUE_ROOT -type f -name \*$hash\*`
 if [ -z "$isDup" ]; then
     mv $jobFile  $(shortestQueue)/job_$($DATE -u +%Y%m%d_%H%M%Sz)_$hash
 else
-echo its a dup
+    #echo "Job already queued ($1) - ${0##*/} cancelled."
     rm -f $jobFile
+    rm -f $QUEUE_ROOT/q*/tmp_*    #also fix any aborted cleanups
+    exit 100
 fi
 
diff --git a/bin/scheduleJobs b/bin/scheduleJobs
--- a/bin/scheduleJobs
+++ b/bin/scheduleJobs
@@ -7,15 +7,15 @@
 ###############################################################################
 # Jobs
 #   Implemented as runnable files (typically shell scripts) within directories
-#   named as JOBS_ROOT.NNNN where NNNN is the duration in minutes after the
+#   named as JOB_ROOT.NNNN where NNNN is the duration in minutes after the
 #   last successful run of the job that the job should be (re)queued for 
 #   execution
 #
 #   Example: if the configuration variable JOB_ROOT is ~/backupGT/jobs/ then
-#   the runJobs script will find directories named ~/backupGT/jobs/jobs.NNNN.
+#   this script will find directories named ~/backupGT/jobs/jobs.NNNN.
 #   If then, ~/backupGT/jobs/job.14400 exists then for each job file found
-#   directly within ~/backupGT/jobs/job.14400, a check will frequently be made
-#   to see that the job has successfully been run within the last 14400 minutes
+#   directly within ~/backupGT/jobs/job.14400, a check will be made to see
+#   that the job has successfully been run within the last 14400 minutes
 #   (1 day in this example).  
 #  
 # Job Status
@@ -34,7 +34,7 @@
 ###############################################################################
 # get user defined globals
 ###############################################################################
-. ${0%/*}/server.conf
+. ${0%/*}/../etc/server.conf
 
 # redefine $SUDO to include the configured user
 SUDO=""
@@ -54,23 +54,25 @@ LAST_MODIFIED_DATE='2012-06-28'
 ###############################################################################
 printFullUsage() {
     $ECHO "###############################################################################"
-    $ECHO "# runJobs (part of the backupGT suite)"
+    $ECHO "# scheduleJobs (part of the backupGT suite)"
     $ECHO "# Author: Garry Thuna"
     $ECHO "# Created: 11/10/2009"
     $ECHO "# Last modified: ${LAST_MODIFIED_DATE}"
     $ECHO "###############################################################################"
     $ECHO
-    $ECHO "Usage: $0"
+    $ECHO "Usage: $0 [-v]"
     $ECHO "   search the JOB_ROOT for job files that have not successfully completed"
     $ECHO "   within the last NNNN minutes.  NNNN is determined by the name of the "
     $ECHO "   directory (which must be job.NNNN) in which the job file is found."
+    $ECHO 
+    $ECHO "  -v  verbose: prints detail of processing to stdout. "
     exit 1
 }
 
 
 
 printMiniUsage() {
-    $ECHO "Usage: $0"
+    $ECHO "Usage: $0 [-v]"
 }
 
 
@@ -98,20 +100,31 @@ COMMAND_PATH=`$READLINK -f "$0"`
 COMMAND_PARMS=( "$@" )
 
 checkRunningUser
-case "$#" in
-    0) ;;
-    *) printFullUsage ;;
-esac
+while getopts ":v" arg; do
+    case $arg in
+        v) VERBOSE="1" ;;
+        *) $ECHO "Option -${OPTARG} not recognized as a valid option." 1>&2
+           printFullUsage 1>&2
+           exit 1
+           ;;
+    esac
+done
 
 for jobDir in `$FIND $JOB_ROOT -name 'jobs.[0-9]*' -mindepth 1 -maxdepth 1`; do   # all the job directories with time periods 
     for jobPath in `$FIND $jobDir -perm -0100 -type f -mindepth 1 -maxdepth 1`; do   # all the jobs in the current job directory
         for statusPath in `find ${jobDir} -name ${jobPath##*/}'*_FAILURE' -o -name ${jobPath##*/}'*_SUCCESS'`; do 
 
             modName=`$AWK '/^# modName:/ {print $3}' "${statusPath}"`
+            [ "$VERBOSE" ] && echo -n  job=$jobPath module=$modName '... '
 
             case "${statusPath##*_}" in
                 FAILURE)
                     "${COMMAND_PATH%/*}/enqueue" "$jobPath" "-s" "$modName"
+                    if [ $? -eq 100 ]; then
+                        [ "$VERBOSE" ] && echo 'attempted enqueue (failure status file found) but job already queued'
+                    else
+                        [ "$VERBOSE" ] && echo 'ENQUEUED (failure status file found)'
+                    fi
                     ;;
 
                 SUCCESS)
@@ -124,11 +137,18 @@ for jobDir in `$FIND $JOB_ROOT -name 'jobs.[0-9]*' -mindepth 1 -maxdepth 1`; do 
                         linux) op="-mmin";  opArg="-${interval}"  ;;
                     esac
                     if $FIND "${jobPath}*SUCCESS" -maxdepth 1 -mindepth 1 $op $opArg; then
+                        [ "$VERBOSE" ] && echo 'skipped (recent success status file found)'
                         continue  #there is a sufficiently recent SUCCESS status file
                     fi
     
                     # else need to enqueue it
                     "${COMMAND_PATH%/*}/enqueue" "$jobPath" "-s" "$modName"
+                    [ "$VERBOSE" ] && echo 'ENQUEUED (last success too old)'
+                    if [ $? -eq 100 ]; then
+                        [ "$VERBOSE" ] && echo 'attempted enqueue (last success too old) but job already queued'
+                    else
+                        [ "$VERBOSE" ] && echo 'ENQUEUED (last success too old)'
+                    fi
                     ;;
             esac
         done
