- finished coding of job control changes - no testing yet done

diff --git a/bin/runQueue b/bin/runQueue
--- a/bin/runQueue
+++ b/bin/runQueue
@@ -1,13 +1,9 @@
 #! /usr/local/bin/bash
 
 ###############################################################################
-# This script finds the job at the head of a queue and runs it.
-###############################################################################
-# Queue entries
-#   Are files with names of the form "qe_pp-timestamp_desc_<crc32>" and
-#   which have as their first line of content the full path name of the job
-#   executable to run, followed by a line for each parameter to place on the
-#   command line when the job is run.
+# This script spawns multiple copies of itself and each copy pulls and runs
+# the job at the top of the queue (priority / FIFO order).
+#
 ###############################################################################
 
 
@@ -40,13 +36,24 @@ printFullUsage() {
     $ECHO "# Created: 11/10/2009"
     $ECHO "# Last modified: ${LAST_MODIFIED_DATE}"
     $ECHO "###############################################################################"
-    $ECHO
     $ECHO "Usage: $0 [<runnerNumber>]"
+    $ECHO "   This script spawns multiple copies of itself and each copy pulls and runs"
+    $ECHO "   the job at the top of the queue (priority / FIFO order)."
+    $ECHO "Options:"
     $ECHO "   runnerNumber: a unique id to identify an instance of this script"
     $ECHO "                 from other instances. runnerNumber will be in the"
     $ECHO "                 range 1 to QUEUE_RUNNERS"
     $ECHO "   if called without the runnerNumber parameter then QUEUE_RUNNERS"
     $ECHO "   instances will be spawned each with a distinct runnerNumber"
+    $ECHO 
+    $ECHO " If the queued job does not specify a module then the job will be invoked"
+    $ECHO " with the -j option, and if a module is specified the job will be invoked"
+    $ECHO " with the -s."
+    $ECHO 
+    $ECHO " All job files must accept additional command line parameters and in turn "
+    $ECHO " append them to the command line when calling backupGT.  Furthermore the"
+    $ECHO " return code from the job file should be 0 for success, non-zero for failure"
+    $ECHO " as returned from backupGT."
     exit 1
 }
 
@@ -71,6 +78,7 @@ printMiniUsage() {
 #       - remove the mutex
 ###############################################################################
 checkRunningUser
+
 case "$#" in
     0) for qrNum in `$SEQ $QUEUE_RUNNERS`; do
            $0 ${qrNum} &    # re-launch this script for each queueRunner
@@ -117,43 +125,53 @@ for mutex in $queueDir/mutex_${qrNum}*; do
 done
 
 # okay lets get the head of the queue
-queueEntry=`$LS $queueDir/qe_* 2>/dev/null | $HEAD -1`
-if [ -z "$queueEntry" ]; then
+firstQueuedJob=`$LS $queueDir/qj_* 2>/dev/null | $HEAD -1`
+if [ -z "$firstQueuedJob" ]; then
     # no jobs left to run
     $RM -f $thisMutex
     exit 0
 fi
 
 # rename it to ensure that we have exclusive control of the entry
-mxqe="$queueDir/mx_${qrNum}_${queueFile}"
-$MV "$queueDir/$queueFile" "$mxqe" 2>/dev/null
-if [ ! -f "$mxqe" ];
+mxqj="$queueDir/mx_${qrNum}_${firstQueuedJob}"
+$MV "$queueDir/$firstQueuedJob" "$mxqj" 2>/dev/null
+if [ ! -f "$mxqj" ];
     # some other queueRunner grabbed the entry before us
     $RM -f $thisMutex
     exec $0 $* &    # try again
 fi
 
-# so now we have a queue entry lets run it and update the status
-jobDir=` $AWK '/^# jobDir:/  {print $3}' "${mxqe}"`
-jobFile=`$AWK '/^# jobFile:/ {print $3}' "${mxqe}"`
-modName=`$AWK '/^# modName:/ {print $3}' "${mxqe}"`
-$mxqe
-rc=$?
-if [ $? -eq 0 ]; then   #success
-    modLine=`$GREP "^${modName}	" ${jobDir}/${JOB_MODLIST_PREFIX}${jobFile}`
-    modLine=`$ECHO $modLine | makeAssignment curState SUCCESS`
-    modLine=`$ECHO $modLine | makeAssignment lastSuccessTimeStamp $timeStamp`
-    modLine=`$ECHO $modLine | makeAssignment lastSuccessDate $(timeStamp2Date $timeStamp)`
-    $SED -i "/^${modName}	/s/.*/${modLine}/" ${jobDir}/${JOB_MODLIST_PREFIX}${jobFile}
-else #failure
-    modLine=`$GREP "^$modName	" ${jobDir}/${JOB_MODLIST_PREFIX}${jobFile}`
-    modLine=`$ECHO $modLine | makeAssignment curState SUCCESS`
-    modLine=`$ECHO $modLine | makeAssignment lastFailureTimeStamp $timeStamp`
-    modLine=`$ECHO $modLine | makeAssignment lastFailureDate $(timeStamp2Date $timeStamp)`
-    $SED -i "/^${modName}	/s/.*/${modLine}/" ${jobDir}/${JOB_MODLIST_PREFIX}${jobFile}
+# so now we have a queue entry lets run it
+jobDir=` $AWK '/^jobDir:/  {print $2}' "${mxqj}"`
+jobFile=`$AWK '/^jobFile:/ {print $2}' "${mxqj}"`
+modName=`$AWK '/^modName:/ {print $2}' "${mxqj}"`
+if [ -z "$modName" ]; then
+    ${jobDir}/${jobFile} -j ${jobDir}/${jobFile}${JOB_MODLIST_SUFFIX}
+    rc=$?
+else
+    ${jobDir}/${jobFile} -s "$modName"
+    rc=$?
 fi
 
+# lets append a status entry to the status file
+statusDir="${jobDir}/${jobFile}${JOB_STATUS_DIR_SUFFIX}"
+statusPath="${statusDir}/${modName}"
+statLine=`$SORT -n $statusPath 2>/dev/null | $TAIL -1`
+if [ "$rc" -eq 0 ]; then
+    statLine=`$ECHO "$statLine" | makeAssignment curState SUCCESS`
+    statLine=`$ECHO "$statLine" | makeAssignment lastSuccessTimeStamp $timeStamp`
+    statLine=`$ECHO "$statLine" | makeAssignment lastSuccessDate $(timeStamp2Date $timeStamp)`
+else
+    statLine=`$ECHO "$statLine" | makeAssignment curState SUCCESS`
+    statLine=`$ECHO "$statLine" | makeAssignment lastFailureTimeStamp $timeStamp`
+    statLine=`$ECHO "$statLine" | makeAssignment lastFailureDate $(timeStamp2Date $timeStamp)`
+fi
+$MKDIR -p $statusDir    #ensure that the job status dir exists
+$ECHO "$statLine" >> $statusPath
+
 # dequeue completed job and cleanup
-$RM -f $mxqe
+$RM -f $mxqj
 $RM -f $thisMmutex
 
+# restart next instance of this queueRunner
+exec $0 ${qrNum} 
diff --git a/bin/scheduleJobs b/bin/scheduleJobs
--- a/bin/scheduleJobs
+++ b/bin/scheduleJobs
@@ -5,30 +5,29 @@
 # time interval and queues them for execution
 #
 ###############################################################################
-# todo: rewrite these descriptions
 # Jobs
 #   Implemented as runnable files (typically shell scripts) within directories
-#   named as JOB_ROOT.NNNN where NNNN is the duration in minutes after the
-#   last successful run of the job that the job should be (re)queued for 
-#   execution
+#   subordinate to JOB_ROOT.  Jobs will be managed if they are executable and
+#   located in a direcotry that also contains a JOB_CONTROL file.
 #
-#   Example: if the configuration variable JOB_ROOT is ~/backupGT/jobs/ then
-#   this script will find directories named ~/backupGT/jobs/jobs.NNNN.
-#   If then, ~/backupGT/jobs/job.14400 exists then for each job file found
-#   directly within ~/backupGT/jobs/job.14400, a check will be made to see
-#   that the job has successfully been run within the last 14400 minutes
-#   (1 day in this example).  
-#  
+# Job ModList
+#   Associated with each job is a modList file named the same as the jobFile
+#   but with $JOB_MODLIST_SUFFIX appended.
+#   The modification date of this modList file is used to indicate how recently
+#   the job ran. If present it will contain the module list as supplied by
+#   the target host.
+#   
+#   When present (and recent) each module listed will be checked to see that it
+#   has had a successful completion within the JOB_INTERVAL (specified in the
+#   JOB_CONTROL file). If not it will be scheduled (enqueued) to run.  Failed
+#   jobs will only be re-scheduled after a minimum wait of JOB_RETRY_INTERVAL.  # 
 # Job Status
-#   The need to re-queue a job (lack of successful completion) is determined as
-#   follows:
-#         - if there is a status file for the job that indicates 
-#           the job did not complete successfully (ie the status file
-#           name will contain the string FAILURE)
-#         - see if there is a status file for the job whose modification
-#           time is older than the prescribed interval
-#         - there are no status files for this job
-# 
+#   Associated with each job is a statud directory named the same as the jobFile
+#   but with $JOB_STATUS_DIR_SUFFIX appended.
+#   Within this directory there will be one status file for each module that has
+#   been previously queued and run.  After each run of the job a line will be
+#   appended with the job's completion status and some additional job control
+#   information.
 ###############################################################################
 
 
@@ -61,12 +60,12 @@ printFullUsage() {
     $ECHO "# Created: 11/10/2009"
     $ECHO "# Last modified: ${LAST_MODIFIED_DATE}"
     $ECHO "###############################################################################"
-    $ECHO
     $ECHO "Usage: $0 [-v]"
     $ECHO "   search the JOB_ROOT for job files that have not successfully completed"
-    $ECHO "   within the last NNNN minutes.  NNNN is determined by the name of the "
-    $ECHO "   directory (which must be job.NNNN) in which the job file is found."
-    $ECHO 
+    $ECHO "   within their prescribed JOB_INTERVAL (as specified in the JOB_CONTROL"
+    $ECHO "   file to be found in the same directory as the job file) and queue them"
+    $ECHO "   to run."
+    $ECHO "Options:"
     $ECHO "  -v  verbose: prints detail of processing to stdout. "
     exit 1
 }
@@ -77,32 +76,38 @@ printMiniUsage() {
 }
 
 
+parseOptions() {
+    while getopts ":v" arg; do
+        case $arg in
+            v) VERBOSE="1" ;;
+            *) $ECHO "Option -${OPTARG} not recognized as a valid option." 1>&2
+               printFullUsage 1>&2
+               exit 1
+               ;;
+        esac
+    done
+    shift $(( OPTIND - 1 ))
+}
+
+
 ###############################################################################
 # main
 ###############################################################################
-COMMAND_PATH=`$READLINK -f "$0"`
-COMMAND_PARMS=( "$@" )
-
 checkRunningUser
-while getopts ":v" arg; do
-    case $arg in
-        v) VERBOSE="1" ;;
-        *) $ECHO "Option -${OPTARG} not recognized as a valid option." 1>&2
-           printFullUsage 1>&2
-           exit 1
-           ;;
-    esac
-done
+parseOptions
 
-for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do   # all the job directories with a JOB_CONTROL file
+# find all the job directories with a JOB_CONTROL file
+for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do
     jobDir=${jobControlFile%/*}
     [ "$VERBOSE" ] && echo "job dir: $jobDir"
 
-    JOB_INTERVAL=1440     #set default 1 day
-    JOB_RETRY_FAILED=60   #set default 1 hour
+    JOB_INTERVAL=1440      #set default 1 day
+    JOB_RETRY_INTERVAL=60  #set default 1 hour
+    JOB_PRIORITY=50        #set default
     . $jobControlFile
 
-    for jobPath in `$FIND $jobDir -perm -0100 -type f -mindepth 1 -maxdepth 1`; do   # all the jobs in the current job directory
+    # find all the jobs in the current job directory
+    for jobPath in `$FIND $jobDir -perm -0100 -type f -mindepth 1 -maxdepth 1`; do
         jobFile=${jobPath##*/}
         [ "$VERBOSE" ] && echo "    job: $jobFile"
 
@@ -116,11 +121,15 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do   # all the job d
             bsd)   findOp="-ctime -${JOB_INTERVAL}m" ;;
             linux) findOp="-mmin  -${JOB_INTERVAL}"  ;;
         esac
-	recentModList="`$FIND ${jobDir} -name ${JOB_MODLIST_PREFIX}${jobFile} $findOp 2>/dev/null`"
+	recentModList="`$FIND ${jobDir} -name ${jobFile}${JOB_MODLIST_SUFFIX} $findOp 2>/dev/null`"
         if [ -z "$recentModList" ]; then
             [ "$VERBOSE" ] && echo "        ENQUEING (modlist missing or older than $JOB_INTERVAL min)"
 #todo purge queues of any instances of this job
-            ${COMMAND_PATH%/*}/enqueue "$jobPath" "-j" "$jobPath" "-q"
+            "${BACKUPGT_ROOT}/enqueue" \
+                "-j" "$jobPath"        \
+                "-s" ""                \
+                "-p" "$JOB_PRIORITY"   \
+                "--"
             continue
         fi
         
@@ -129,11 +138,13 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do   # all the job d
         #----------------
         $CAT $recentModList | while read modName modComment; do
             [ "$VERBOSE" ] && echo '        mod: ' $modName
-            modLine=`grep "^$modName	" "${jobDir}/${JOB_STATUS_PREFIX}${jobFile}" 2>/dev/null`
-            curState=`            echo "$modLine" | parseAssignment curState`
-            lastSuccessTimeStamp=`echo "$modLine" | parseAssignment lastSuccessTimeStamp`
-            lastFailureTimeStamp=`echo "$modLine" | parseAssignment lastFailureTimeStamp`
-         
+            statusDir="${jobDir}/${jobFile}${JOB_STATUS_DIR_SUFFIX}"
+            statusPath="${statusDir}/${modName}"
+            statLine=`$SORT -n $statusPath 2>/dev/null | $TAIL -1`
+
+            curState=`            echo "$statLine" | parseAssignment curState`
+            lastSuccessTimeStamp=`echo "$statLine" | parseAssignment lastSuccessTimeStamp`
+            lastFailureTimeStamp=`echo "$statLine" | parseAssignment lastFailureTimeStamp`
             
             case x$curState in
                 xSUCCESS)
@@ -146,12 +157,12 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do   # all the job d
                     fi
                     ;;
                 xFAILURE)
-                    maxAge=`$EXPR $JOB_RETRY_FAILED \* 60`
+                    maxAge=`$EXPR $JOB_RETRY_INTERVAL \* 60`
 		    needToQueue=`isTimeStampTooOld ${lastFailureTimeStamp:-1} $maxAge`
                     if [ $needToQueue ]; then
-                        [ "$VERBOSE" ] && echo "            ENQUEUE: curState=$curState wait period $JOB_RETRY_FAILED expired"
+                        [ "$VERBOSE" ] && echo "            ENQUEUE: curState=$curState wait period $JOB_RETRY_INTERVAL expired"
                     else
-                        [ "$VERBOSE" ] && echo "            curState=$curState too recent (wait $JOB_RETRY_FAILED before retry)"
+                        [ "$VERBOSE" ] && echo "            curState=$curState too recent (wait $JOB_RETRY_INTERVAL before retry)"
                     fi
                     ;;
                 *)
@@ -161,7 +172,11 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do   # all the job d
             esac
         
             if [ $needToQueue ]; then
-                "${COMMAND_PATH%/*}/enqueue" "$jobPath" "-j" "$jobPath" "-s" "$modName"
+                "${BACKUPGT_ROOT}/enqueue" \
+                    "-j" "$jobPath"        \
+                    "-s" "$modName"        \
+                    "-p" "$JOB_PRIORITY"   \
+                    "--"
                 if [ $? -eq 100 ]; then
                     [ "$VERBOSE" ] && echo '            attempted enqueue but job already queued'
                 fi
