- runQueue seems to be working - now lets finish testing the scheduleJobs

diff --git a/bin/runQueue b/bin/runQueue
--- a/bin/runQueue
+++ b/bin/runQueue
@@ -36,7 +36,7 @@ printFullUsage() {
     $ECHO "# Created: 11/10/2009"
     $ECHO "# Last modified: ${LAST_MODIFIED_DATE}"
     $ECHO "###############################################################################"
-    $ECHO "Usage: $0 [<runnerNumber>]"
+    $ECHO "Usage: $0 [-v] [<runnerNumber>]"
     $ECHO "   This script spawns multiple copies of itself and each copy pulls and runs"
     $ECHO "   the job at the top of the queue (priority / FIFO order)."
     $ECHO "Options:"
@@ -63,6 +63,23 @@ printMiniUsage() {
 }
 
 
+parseOptions() {
+    local opSsupplied
+    while getopts ":v" arg; do
+        case $arg in
+            v) VERBOSE="1" ;;
+            :) $ECHO "Option -${OPTARG} requires an argument." 1>&2
+               exit 1
+               ;;
+            *) $ECHO "Option -${OPTARG} not recognized as a valid option." 1>&2
+               exit 1
+               ;;
+        esac
+    done
+    COMMAND_LINE_PARMS=( "${@:$OPTIND}" )  #save rest of command line as array
+}
+
+
 ###############################################################################
 # main
 #   - create a queueRunner specific mutex in the queue (mark with a timestamp)
@@ -78,10 +95,12 @@ printMiniUsage() {
 #       - remove the mutex
 ###############################################################################
 checkRunningUser
+parseOptions "$@"; set -- "${COMMAND_LINE_PARMS[@]}"
 
 case "$#" in
     0) for qrNum in `$SEQ $QUEUE_RUNNERS`; do
-           $0 ${qrNum} &    # re-launch this script for each queueRunner
+           [ "$VERBOSE" ] && $ECHO "${0}: spawning queueRunner $qrNum"
+           $0 `[ "$VERBOSE" ] && $ECHO "-v"` ${qrNum} &
        done
        exit
        ;;
@@ -93,29 +112,32 @@ case "$#" in
        ;;
 esac
 
-queueDir="$QUEUE_ROOT"
 
 # check that the queueDir exists
+queueDir="$QUEUE_ROOT"
 if [ ! -d "$queueDir" ]; then
     $ECHO "$0: ERROR: queue direcotry '$queueDir' does not exist"
     exit 1
 fi
 
-# create a mutex in the queue (mark with a timestamp
+
+# create a mutex in the queue (mark with a timestamp)
 timeStamp=`$DATE -u +%s`
 thisMutex=`$MKTEMP $queueDir/mutex_${qrNum}_${timeStamp}_XXXXX`
 $ECHO "$$" > $thisMutex
 $SLEEP 1
 
+
 # see if thisMutex is governing for this qrNum
 for mutex in $queueDir/mutex_${qrNum}*; do
+    [ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) checking mutex $mutexPid"
     if [ "$mutex" = $thisMutex ]; then
         #this mutex is controlling
         break
     fi
     mutexPid=`$CAT $mutex`
     if $PS -o pid,command -p $mutexPid | $GREP -q "^$mutexPid"; then
-        # other queueRunner is still running
+        [ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) another istance is controlling - exiting"
         $RM -f $thisMutex
         exit 0
     else
@@ -123,55 +145,68 @@ for mutex in $queueDir/mutex_${qrNum}*; do
         $RM -f $mutex
     fi
 done
+[ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) is controlling mutex=${thisMutex##*/}"
+
 
 # okay lets get the head of the queue
-firstQueuedJob=`$LS $queueDir/qj_* 2>/dev/null | $HEAD -1`
-if [ -z "$firstQueuedJob" ]; then
-    # no jobs left to run
+firstQueuedJobPath=`$LS $queueDir/qj_* 2>/dev/null | $HEAD -1`
+if [ -z "$firstQueuedJobPath" ]; then
+    [ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) queue is empty - exiting"
     $RM -f $thisMutex
     exit 0
 fi
+[ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) queue head is ${firstQueuedJobPath##*/}"
+
 
 # rename it to ensure that we have exclusive control of the entry
-mxqj="$queueDir/mx_${qrNum}_${firstQueuedJob}"
-$MV "$queueDir/$firstQueuedJob" "$mxqj" 2>/dev/null
-if [ ! -f "$mxqj" ];
-    # some other queueRunner grabbed the entry before us
+mxqj="$queueDir/mx_${qrNum}_${firstQueuedJobPath##*/}"
+$MV "$firstQueuedJobPath" "$mxqj" 2>/dev/null
+if [ ! -f "$mxqj" ]; then
+    [ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) competing queue runnerqueue took head; restarting"
     $RM -f $thisMutex
-    exec $0 $* &    # try again
+    exec $0 `[ "$VERBOSE" ] && $ECHO "-v"` ${qrNum}
 fi
+[ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) has dequeued head as ${mxqj##*/}"
+
 
 # so now we have a queue entry lets run it
 jobDir=` $AWK '/^jobDir:/  {print $2}' "${mxqj}"`
 jobFile=`$AWK '/^jobFile:/ {print $2}' "${mxqj}"`
 modName=`$AWK '/^modName:/ {print $2}' "${mxqj}"`
 if [ -z "$modName" ]; then
-    ${jobDir}/${jobFile} -j ${jobDir}/${jobFile}${JOB_MODLIST_SUFFIX}
+#    ${jobDir}/${jobFile} -j ${jobDir}/${jobFile}${JOB_MODLIST_SUFFIX}
     rc=$?
 else
-    ${jobDir}/${jobFile} -s "$modName"
+#    ${jobDir}/${jobFile} -s "$modName"
     rc=$?
 fi
 
+
 # lets append a status entry to the status file
 statusDir="${jobDir}/${jobFile}${JOB_STATUS_DIR_SUFFIX}"
-statusPath="${statusDir}/${modName}"
-statLine=`$SORT -n $statusPath 2>/dev/null | $TAIL -1`
+statusPath="${statusDir}/${modName:-_listModules}"
+statLine=`$SORT $statusPath 2>/dev/null | $TAIL -1`
 if [ "$rc" -eq 0 ]; then
+    [ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) success - updating status"
+    statLine=`$ECHO "$statLine" | makeAssignment curTimeStamp $(timeStamp2Date $timeStamp)`
     statLine=`$ECHO "$statLine" | makeAssignment curState SUCCESS`
     statLine=`$ECHO "$statLine" | makeAssignment lastSuccessTimeStamp $timeStamp`
-    statLine=`$ECHO "$statLine" | makeAssignment lastSuccessDate $(timeStamp2Date $timeStamp)`
+    statLine=`$ECHO "$statLine" | makeAssignment lastSuccessDate $(timeStamp2Date $timeStamp)z`
 else
-    statLine=`$ECHO "$statLine" | makeAssignment curState SUCCESS`
+    [ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) failure - updating status"
+    statLine=`$ECHO "$statLine" | makeAssignment curTimeStamp $(timeStamp2Date $timeStamp)`
+    statLine=`$ECHO "$statLine" | makeAssignment curState FAILURE`
     statLine=`$ECHO "$statLine" | makeAssignment lastFailureTimeStamp $timeStamp`
-    statLine=`$ECHO "$statLine" | makeAssignment lastFailureDate $(timeStamp2Date $timeStamp)`
+    statLine=`$ECHO "$statLine" | makeAssignment lastFailureDate $(timeStamp2Date $timeStamp)z`
 fi
 $MKDIR -p $statusDir    #ensure that the job status dir exists
 $ECHO "$statLine" >> $statusPath
 
 # dequeue completed job and cleanup
 $RM -f $mxqj
-$RM -f $thisMmutex
+$RM -f $thisMutex
 
 # restart next instance of this queueRunner
-exec $0 ${qrNum} 
+[ "$VERBOSE" ] && $ECHO "queueRunner_$qrNum ($$) exec'ing new instance."
+exec $0 `[ "$VERBOSE" ] && $ECHO "-v"` ${qrNum}
+
diff --git a/bin/scheduleJobs b/bin/scheduleJobs
--- a/bin/scheduleJobs
+++ b/bin/scheduleJobs
@@ -80,13 +80,16 @@ parseOptions() {
     while getopts ":v" arg; do
         case $arg in
             v) VERBOSE="1" ;;
+            :) $ECHO "Option -${OPTARG} requires an argument." 1>&2
+               exit 1
+               ;;
             *) $ECHO "Option -${OPTARG} not recognized as a valid option." 1>&2
                printFullUsage 1>&2
                exit 1
                ;;
         esac
     done
-    shift $(( OPTIND - 1 ))
+    COMMAND_LINE_PARMS=( "${@:$OPTIND}" )  #save rest of command line as array
 }
 
 
@@ -94,12 +97,12 @@ parseOptions() {
 # main
 ###############################################################################
 checkRunningUser
-parseOptions "$@"
+parseOptions "$@"; set -- "${COMMAND_LINE_PARMS[@]}"
 
 # find all the job directories with a JOB_CONTROL file
 for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do
     jobDir=${jobControlFile%/*}
-    [ "$VERBOSE" ] && echo "job dir: ${jobDir##*/}  ($jobDir)"
+    [ "$VERBOSE" ] && $ECHO "job dir: ${jobDir##*/}  ($jobDir)"
 
     JOB_INTERVAL=1440      #set default 1 day
     JOB_RETRY_INTERVAL=60  #set default 1 hour
@@ -109,7 +112,7 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do
     # find all the jobs in the current job directory
     for jobPath in `$FIND $jobDir -perm -0100 -type f -mindepth 1 -maxdepth 1`; do
         jobFile=${jobPath##*/}
-        [ "$VERBOSE" ] && echo "    job: $jobFile"
+        [ "$VERBOSE" ] && $ECHO "    job: $jobFile"
 
         # if a custom job control file exists then source it
         [ -f "${jobPath}${JOB_CONTROL}" ] && . "${jobPath}${JOB_CONTROL}"
@@ -123,7 +126,7 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do
         esac
 	recentModList="`$FIND ${jobDir} -name ${jobFile}${JOB_MODLIST_SUFFIX} $findOp 2>/dev/null`"
         if [ -z "$recentModList" ]; then
-            [ "$VERBOSE" ] && echo "        ENQUEING (modlist missing or older than $JOB_INTERVAL min)"
+            [ "$VERBOSE" ] && $ECHO "        ENQUEING (modlist missing or older than $JOB_INTERVAL min)"
 #todo purge queues of any instances of this job
             "${BACKUPGT_ROOT}/bin/enqueue"     \
                 `[ "$VERBOSE" ] && $ECHO "-v"` \
@@ -138,37 +141,37 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do
         # now consider the modules
         #----------------
         $CAT $recentModList | while read modName modComment; do
-            [ "$VERBOSE" ] && echo '        mod: ' $modName
+            [ "$VERBOSE" ] && $ECHO '        mod: ' $modName
             statusDir="${jobDir}/${jobFile}${JOB_STATUS_DIR_SUFFIX}"
             statusPath="${statusDir}/${modName}"
-            statLine=`$SORT -n $statusPath 2>/dev/null | $TAIL -1`
+            statLine=`$SORT $statusPath 2>/dev/null | $TAIL -1`
 
-            curState=`            echo "$statLine" | parseAssignment curState`
-            lastSuccessTimeStamp=`echo "$statLine" | parseAssignment lastSuccessTimeStamp`
-            lastFailureTimeStamp=`echo "$statLine" | parseAssignment lastFailureTimeStamp`
+            curState=`            $ECHO "$statLine" | parseAssignment curState`
+            lastSuccessTimeStamp=`$ECHO "$statLine" | parseAssignment lastSuccessTimeStamp`
+            lastFailureTimeStamp=`$ECHO "$statLine" | parseAssignment lastFailureTimeStamp`
             
             case x$curState in
                 xSUCCESS)
                     maxAge=`$EXPR $JOB_INTERVAL \* 60`
 		    needToQueue=`isTimeStampTooOld ${lastSuccessTimeStamp:-1} $maxAge`
                     if [ $needToQueue ]; then
-                        [ "$VERBOSE" ] && echo "            ENQUEUE: curState=$curState too old ($JOB_INTERVAL max age)"
+                        [ "$VERBOSE" ] && $ECHO "            ENQUEUE: curState=$curState too old ($JOB_INTERVAL max age)"
                     else
-                        [ "$VERBOSE" ] && echo "            curState=$curState sufficiently recent ($JOB_INTERVAL max age)"
+                        [ "$VERBOSE" ] && $ECHO "            curState=$curState sufficiently recent ($JOB_INTERVAL max age)"
                     fi
                     ;;
                 xFAILURE)
                     maxAge=`$EXPR $JOB_RETRY_INTERVAL \* 60`
 		    needToQueue=`isTimeStampTooOld ${lastFailureTimeStamp:-1} $maxAge`
                     if [ $needToQueue ]; then
-                        [ "$VERBOSE" ] && echo "            ENQUEUE: curState=$curState wait period $JOB_RETRY_INTERVAL expired"
+                        [ "$VERBOSE" ] && $ECHO "            ENQUEUE: curState=$curState wait period $JOB_RETRY_INTERVAL expired"
                     else
-                        [ "$VERBOSE" ] && echo "            curState=$curState too recent (wait $JOB_RETRY_INTERVAL before retry)"
+                        [ "$VERBOSE" ] && $ECHO "            curState=$curState too recent (wait $JOB_RETRY_INTERVAL before retry)"
                     fi
                     ;;
                 *)
 		    needToQueue=0  #0=true   
-                    [ "$VERBOSE" ] && echo "            ENQUEUE: no prior state"
+                    [ "$VERBOSE" ] && $ECHO "            ENQUEUE: no prior stats"
                     ;;
             esac
         
@@ -180,7 +183,7 @@ for jobControlFile in `$FIND $JOB_ROOT -name $JOB_CONTROL`; do
                     "-p" "$JOB_PRIORITY"           \
                     "--"
                 if [ $? -eq 100 ]; then
-                    [ "$VERBOSE" ] && echo '            attempted enqueue but job already queued'
+                    [ "$VERBOSE" ] && $ECHO '            attempted enqueue but job already queued'
                 fi
             fi
 
